name: Deploy                      # Actions 显示的名字，随意设置
on: [push]                        # 监听到 push 事件后触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout              # 拉取当前执行 Actions 仓库的指定分支
      uses: actions/checkout@v2
      with:
        ref: main                 # 注意选择私人仓库是main还是master分支

    - name: Setup Node            # 使用node 14
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: NPM INSTALL           #安装依赖
      run: |
        npm install hexo-cli -g
        npm install hexo-deployer-git  --save 
        npm install

    - name: Add KEY               #这里需要提供一个ssh私钥，用你平时常用机器里的 ~/.ssh/id_rsa即可
      env:
        SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE" > ~/.ssh/id_rsa
        chmod 700 -R ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "paulmiao@me.com"
        git config --global user.name "miaoyanginfo"

    - name: Hexo Deploy           # hexo deploy 会自动build然后上传到github.io项目中
      run: |
        hexo clean
        hexo deploy  
